<header class="only-pc">
  <div class="Responsive">
    <div class="Menu">
      <div class="Menu-branch">
        <div class="Menu-branch__logo">
          <img src="/common/img/logo.webp" alt="">
        </div>
        <div class="Menu-branch-search">
          <div class="Menu-branch-search-location">
            <p class="js-locationBtn Menu-branch-search-location__txt">Hà Nội</p>
            <div class="Menu-branch-search-location-select">
              <p class="js-locationOption"><i class="fa fa-map-marker"></i><span>Hà Nội</span></p>
              <p class="js-locationOption"><i class="fa fa-map-marker"></i><span>Hồ Chí Minh</span></p>
            </div>
          </div>
          <div class="Menu-branch-search-input">
            <input type="text" placeholder="tìm kiếm">
          </div>
          <div class="Menu-branch-search-btn">
            <i class="fa fa-search"></i>
          </div>
        </div>
      </div>
      <div class="Menu-list">
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">ĐIỆN THOẠI</p>
          </div>
          <div class="Menu-list-item-sub">
            <div class="Menu-list-item-sub-list">
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">APPLE</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">SAMSUNG</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">XIAOMI</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">OPPO</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">NOKIA</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">REALME</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">VSMART</a>
              </div>
            </div>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fa fa-tablet"></i></div>
            <p class="Menu-list-item-content__txt">TABLET</p>
          </div>
          <div class="Menu-list-item-sub">
            <div class="Menu-list-item-sub-list">
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">iPad Pro</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">iPad 10.2</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">iPad Air</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">iPad 9.7</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">iPad Mini</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">Huawei</a>
              </div>
              <div class="Menu-list-item-sub-item">
                <a href="#" class="Menu-list-item-sub-item__txt">Samsung</a>
              </div>
            </div>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">PHỤ KIỆN</p>
          </div>
          <div class="Menu-list-item-sub">
            <div class="Menu-list-item-sub-item">
              <a href="#" class="Menu-list-item-sub-item__txt">Pin dự phòng</a>
            </div>
            <div class="Menu-list-item-sub-item">
              <a href="#" class="Menu-list-item-sub-item__txt">Cáp sạc</a>
            </div>
            <div class="Menu-list-item-sub-item">
              <a href="#" class="Menu-list-item-sub-item__txt">Dán màn hình</a>
            </div>
            <div class="Menu-list-item-sub-item">
              <a href="#" class="Menu-list-item-sub-item__txt">Ốp lưng</a>
            </div>
            <div class="Menu-list-item-sub-item">
              <a href="#" class="Menu-list-item-sub-item__txt">Thẻ nhớ</a>
            </div>
            <div class="Menu-list-item-sub-item">
              <a href="#" class="Menu-list-item-sub-item__txt">Chuột|Bàn phím</a>
            </div>
            <div class="Menu-list-item-sub-item">
              <a href="#" class="Menu-list-item-sub-item__txt">Camera</a>
            </div>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">ĐỒNG HỒ</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">ÂM THANH</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">LAPTOP</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">SIM THẺ</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">HÀNG CŨ</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">TRẢ GÓP</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">DỊCH VỤ</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">CÔNG NGHỆ</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">ƯU ĐÃI</p>
          </div>
        </div>
        <div class="Menu-list-item">
          <div class="Menu-list-item-content">
            <div class="Menu-list-item-content__ico"><i class="fas fa-mobile-alt"></i></div>
            <p class="Menu-list-item-content__txt">KHUYẾN MÃI</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<header class="only-sp">
  <div class="js-nav Nav">
    <div class="Nav-content">
      <div class="Nav__logo">
        <img src="/common/img/logo.webp" alt="cellphones">
      </div>
      <div class="Nav-search">
        <div class="Nav-search-content">
          <div class="Nav-search__input">
            <input type="text" placeholder="Tìm kiếm">
          </div>
          <div class="Nav-search__btn">
            <i class="fa fa-search"></i>
          </div>
        </div>
      </div>
      <div class="Nav-hamburger">
        <div class="js-navHamburger Nav-hamburger-content">
          <span class="Nav-hamburger-content__ico"></span>
          <span class="Nav-hamburger-content__ico"></span>
          <span class="Nav-hamburger-content__ico"></span>
        </div>
      </div>
    </div>
    <div class="Nav-menu">
      <div class="Nav-menu-content">
        <div class="Nav-menu-content-list">
          <p class="Nav-menu-content-item">Điện thoại</p>
          <p class="Nav-menu-content-item">Tablet</p>
          <p class="Nav-menu-content-item">Phụ kiện</p>
          <p class="Nav-menu-content-item">Đồng hồ</p>
          <p class="Nav-menu-content-item">Âm thanh</p>
          <p class="Nav-menu-content-item">Laptop</p>
          <p class="Nav-menu-content-item">Sim Thẻ</p>
          <p class="Nav-menu-content-item">Hàng cũ</p>
          <p class="Nav-menu-content-item">Trả góp</p>
          <p class="Nav-menu-content-item">Dịch vụ</p>
          <p class="Nav-menu-content-item">Khuyến mãi</p>
          <p class="Nav-menu-content-item">Tin tức</p>
          <p class="Nav-menu-content-item">Thu cũ đổi mới</p>
          <p class="Nav-menu-content-item">Ưu đãi đối tác</p>
        </div>
        <div class="Nav-menu-content-footer">
          <div class="Nav-menu-content-footer-contact">
            <img src="/common/img/contact_free_ico.png" alt="">
            <a href="tel:91919191919">091919191919</a>
          </div>
          <div class="Nav-menu-content-footer-location">
            <p>Nơi mua</p>
            <select>
              <option value="hanoi">Hà Nội</option>
              <option value="hanoi">Hồ Chí Minh</option>
            </select>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
