<div class="User" id="userFragment">
  <div class="User-content">
    <section>
      <div class="User-list">
        <div class="User-list-head">
          <p class="f-50">ID</p>
          <p class="f-full">Tên NV</p>
          <p class="f-150">Mã NV</p>
          <p class="f-100">Phân quyền</p>
          <p class="f-100">Ngày tạo</p>
          <p class="f-130">Hành động</p>
        </div>
        <div id="userList">
        </div>
      </div>
    </section>
    <section>
      <div class="Form-field">
        <span>ID</span>
        <input type="text">
      </div>
      <div class="Form-field">
        <span>Tên nhân viên</span>
        <input type="text">
      </div>
      <div class="Form-field">
        <span>Mã nhân viên</span>
        <input type="text">
      </div>
      <div class="Form-field">
        <span>Phân quyền</span>
        <select>
          <option value="0">Supper Admin</option>
          <option value="1">Admin</option>
          <option value="2">Nhân viên</option>
        </select>
      </div>
      <div class="Form-field">
        <span>Mã nhân viên</span>
        <textarea type="text" rows="6"></textarea>
      </div>
      <div class="User-form-btn">
        <span class="Button">Thêm mới</span>
        <span class="Button User-form-btn__save">Lưu lại</span>
        <span class="Button">Hủy bỏ</span>
      </div>
    </section>
  </div>
</div>
