<div class="User" id="userFragment">
  <div class="User-content">
    <section>
      <div class="User-list">
        <div class="User-list-head">
          <p class="f-50">ID</p>
          <p class="f-full">Tên NV</p>
          <p class="f-150">Mã NV</p>
          <p class="f-100">Phân quyền</p>
          <p class="f-100">Ngày tạo</p>
          <p class="f-130">Hành động</p>
        </div>
        <div id="userList">
        </div>
      </div>
    </section>
    <section>form</section>
  </div>
</div>
